apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    k8s-app: filebeat
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: filebeat
  labels:
    k8s-app: filebeat
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  - "services"
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: kube-system
  name: filebeat
  labels:
    k8s-app: filebeat
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: kube-system
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: ""
